export const ALL_ARCHIVES_REQUEST="ALL_QUESTION_REQUEST";
export const ALL_ARCHIVES_SUCCESS="ALL_QUESTION_SUCCESS";
export const ALL_ARCHIVES_FAIL="ALL_QUESTION_FAIL";


export const CLEAR_ERRORS =" CLEAR_ERRORS";
