export const ALL_QUESTION_REQUEST="ALL_QUESTION_REQUEST";
export const ALL_QUESTION_SUCCESS="ALL_QUESTION_SUCCESS";
export const ALL_QUESTION_FAIL="ALL_QUESTION_FAIL";

export const QUESTION_DETAILS_REQUEST="QUESTION_DETAILS_REQUEST";
export  const QUESTION_DETAILS_SUCCESS="QUESTION_DETAILS_SUCCESS";
export const QUESTION_DETAILS_FAIL="QUESTION_DETAILS_FAIL";


export const NEW_QUESTION_REQUEST = "NEW_QUESTION_REQUEST";
export const NEW_QUESTION_SUCCESS = "NEW_QUESTION_SUCCESS";
export const NEW_QUESTION_RESET = "NEW_QUESTION_RESET";
export const NEW_QUESTION_FAIL = "NEW_QUESTION_FAIL";


export const NEW_ANSWER_REQUEST = "NEW_ANSWER_REQUEST";
export const NEW_ANSWER_SUCCESS = "NEW_ANSWER_SUCCESS";
export const NEW_ANSWER_RESET = "NEW_ANSWER_RESET";
export const NEW_ANSWER_FAIL = "NEW_ANSWER_FAIL";

export const CLEAR_ERRORS =" CLEAR_ERRORS";