export const ALL_QUESTION_REQUEST="ALL_QUESTION_REQUEST";
export const ALL_QUESTION_SUCCESS="ALL_QUESTION_SUCCESS";
export const ALL_QUESTION_FAIL="ALL_QUESTION_FAIL";


export const CLEAR_ERRORS =" CLEAR_ERRORS";